spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api-mundotech
    username: root
    password: 12345

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  secret: MiClaveSuperSecretaYSegura1234567890ABCD
  expiration: 36000000